#ifndef __TIKIRIMC_HEADER_H__
#define __TIKIRIMC_HEADER_H__

enum{
  RT_ALL_NODES = 0x00,
  RT_ROOT_ONLY = 0x80,
};

enum{
  CT_BROADCAST = 0x00,
  CT_UNICAST = 0x20,
  CT_MULTICAST = 0x40,
  CT_SUBTREE_BCAST = 0x60,
};

enum{
  PKT_NULL = 0x00,
  PKT_NETWORK_INIT = 0x01,
  PKT_PARENT_SELECT_REQ = 0x02,
  PKT_PARENT_SELECT_RES_SUBROOT = 0x03,
  PKT_PARENT_SELECT_RES_LEAF = 0x04,
  PKT_ADD_NEW_DECENDENT = 0x05,
  PKT_DECENDENT_ENTRY_REFRESH = 0x06,
  PKT_APPLICATION_LEVEL = 0x07,
  PKT_APPLICATION_LEVEL_UCAST = 0x08,
  PKT_APPLICATION_LEVEL_BCAST = 0x09,
  PKT_APPLICATION_LEVEL_MCAST = 0x0A,
  PKT_MCAST_GROUP_CREATED = 0x0B,
  PKT_MCAST_GROUP_REMOVED = 0x0C,
  PKT_MCAST_GROUP_INVITED = 0x0D,
};

enum{
  MASK_PKT_BITS = 0x1F,
  MASK_CT_BITS = 0x60,
  MASK_RT_BIT = 0x80,
};

#endif /* __TIKIRIMC_HEADER_H__ */
